export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja-jp">
      <body style={{ margin: 0, padding: 0 }}>{children}</body>
    </html>
  )
}

export default RootLayout
