export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}
import "styles/index.css"

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja-jp">
      <head>
        <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
        <title>Alumni book</title>
      </head>
      <body style={{ margin: 0, padding: 0 }}>{children}</body>
    </html>
  )
}

export default RootLayout
